name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt -- --check --config group_imports=StdExternalCrate
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings -W clippy::pedantic
      - name: markdownlint
        uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - name: Install Tarpaulin
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
        run: cargo install cargo-tarpaulin --version 0.18.0-alpha3
      - name: Build
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Generate coverage report
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
        run: cargo tarpaulin --out Xml --avoid-cfg-tarpaulin
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.66.0
      - name: Build
        run: cargo build --verbose --all-features
