name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
        rust: [1.37.0, stable]

    steps:
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install components
      if: matrix.os == 'ubuntu-18.04' && matrix.rust == 'stable'
      run: rustup component add clippy rustfmt
    - name: Check formatting
      if: matrix.os == 'ubuntu-18.04' && matrix.rust == 'stable'
      run: cargo fmt -- --check
    - name: Clippy
      if: matrix.os == 'ubuntu-18.04' && matrix.rust == 'stable'
      run: cargo clippy -- -Dwarnings -W clippy::pedantic
